services:
  # --- INFRAESTRUCTURA ---
  
  # RabbitMQ: Necesario para el REQ15 (comunicación asíncrona)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: chef-rabbitmq
    ports:
      - "5672:5672"   # Puerto de mensajes
      - "15672:15672" # Panel de administración (guest/guest)
    networks:
      - chef-network

  # Keycloak: Necesario para el REQ20 (Autenticación)
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: chef-keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - chef-network

  # --- MICROSERVICIOS ---

  # Servicio de Usuarios (Puerto 3001)
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - SESSION_SECRET=secret_paula_123
      - KEYCLOAK_URL=http://keycloak:8080/
    depends_on:
      - rabbitmq
      - keycloak
    networks:
      - chef-network

  # Servicio de Recetas (Puerto 3002) - REQ14
  recipe-service:
    build: ./services/recipe-service
    container_name: recipe-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - SESSION_SECRET=secret_recetas_456
      - KEYCLOAK_URL=http://keycloak:8080/
    depends_on:
      - keycloak
    networks:
      - chef-network
      recommendation-service:
    build: ./services/recommendation-service
    container_name: recommendation-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - chef-network

networks:
  chef-network:
    driver: bridge