services:
  # --- INFRAESTRUCTURA ---
  mongo:
    image: mongo:latest
    container_name: chef-mongo
    ports:
      - "27017:27017"
    networks:
      - chef-network
  
  # RabbitMQ: Necesario para el REQ15 (comunicación asíncrona)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: chef-rabbitmq
    ports:
      - "5672:5672"   # Puerto de mensajes
      - "15672:15672" # Panel de administración (guest/guest)
    networks:
      - chef-network

  # Keycloak: Necesario para el REQ20 (Autenticación)
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: chef-keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
    networks:
      - chef-network

  # --- MICROSERVICIOS ---

  # Servicio de Usuarios (Puerto 8000)
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - SESSION_SECRET=secret_paula_123
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=ChefMatchRealm
      - KEYCLOAK_CLIENT_ID=account
    depends_on:
      - rabbitmq
      - keycloak
    networks:
      - chef-network

  # Servicio de Recetas (Puerto 8000) - REQ14
  recipe-service:
    build: ./services/recipe-service
    container_name: recipe-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/chefmatch
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=ChefMatchRealm
      - KEYCLOAK_CLIENT_ID=account
    depends_on:
      - rabbitmq
    networks:
      - chef-network

  # DEBE ESTAR AL MISMO NIVEL QUE RECIPE-SERVICE
  recommendation-service:
    build: ./services/recommendation-service
    container_name: recommendation-service
    ports:
      - "8002:8000"
    environment:
      - PORT=8000
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=ChefMatchRealm
      - KEYCLOAK_CLIENT_ID=account
      - MONGODB_URI=mongodb://mongo:27017/chefmatch
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - chef-network

networks:
  chef-network:
    driver: bridge
