apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chef-match-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AlejandroYM/Project_ltu-m7011e.git
    targetRevision: main
    path: Project_ltu-m7011e/k8s # Carpeta donde est√°n los archivos de arriba
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true