# Información del Proyecto
app:
  name: myrecipies

# Configuración de Dominio y Seguridad (REQ23/24)
domain: ltu-m7011e-5.se
email: aleyec-5@student.ltu.se

# Definición de Microservicios para el loop de Helm (REQ11/12)
services:
  user:
    name: user-service
    image: paulacf03/chef-user-service:latest
    port: 3001
    replicas: 2
  recipe:
    name: recipe-service
    image: paulacf03/chef-recipe-service:latest
    port: 3002
    replicas: 1
  recommendation:
    name: recommendation-service
    image: paulacf03/chef-recommendation-service:latest
    port: 3003
    replicas: 1
  frontend:
    name: chef-frontend
    image: paulacf03/chef-frontend:latest
    port: 5173
    replicas: 1