# values.yaml definitivo (Limpio de secretos)
services:
  user:
    name: user-service
    image: aym3/chef-user-service:latest
    port: 8000
    targetPort: 8000
    replicas: 1
  recipe:
    name: recipe-service
    image: aym3/chef-recipe-service:latest
    replicas: 1
    port: 8000
    targetPort: 8000
    
  recommendation:
    name: recommendation-service
    image: aym3/chef-recommendation-service:latest
    port: 8000
    targetPort: 8000
    replicas: 1
  frontend:
    name: chef-frontend
    image: aym3/chef-frontend:latest
    port: 80
    targetPort: 80
    replicas: 1