# Información del Proyecto
app:
  name: myrecipies

# Configuración de Dominio y Seguridad (REQ23/24)
domain: ltu-m7011e-5.se
email: aleyec-5@student.ltu.se

# Definición de Microservicios para el loop de Helm (REQ11/12)
services:
  user:
    name: user-service
    image: alejandroym/chef-user-service:latest # 
  recipe:
    name: recipe-service
    image: alejandroym/chef-recipe-service:latest # 
  recommendation:
    name: recommendation-service
    image: alejandroym/chef-recommendation-service:latest # 
  frontend:
    name: chef-frontend
    image: alejandroym/chef-frontend:latest # 