services:
  user:
    name: user-service
    image: aym3/chef-user-service:v9
    port: 3004 # Ãšnico para User
    replicas: 1
  recipe:
    name: recipe-service
    image: aym3/chef-recipe-service:v9
    port: 3002 # Cambia de 3001 a 3002
    replicas: 1
  recommendation:
    name: recommendation-service
    image: aym3/chef-recommendation-service:v9
    port: 3003 # Cambia de 3001 a 3003
    replicas: 1
  frontend:
    name: chef-frontend
    image: aym3/chef-frontend:latest
    port: 5173
    replicas: 1