services:
  user:
    name: user-service
    image: aym3/chef-user-service:latest
    port: 3001
    replicas: 2
  recipe:
    name: recipe-service
    image: aym3/chef-recipe-service:latest
    port: 3002
    replicas: 1
  recommendation:
    name: recommendation-service
    image: aym3/chef-recommendation-service:latest
    port: 3003
    replicas: 1
  frontend:
    name: chef-frontend
    image: aym3/chef-frontend:latest
    port: 5173
    replicas: 1