services:
  user:
    name: user-service
    port: 8000       # Cambiar a 8000
    targetPort: 8000 # Asegurar que apunte al 8000 del pod
  recipe:
    name: recipe-service
    port: 8000       # Cambiar a 8000
    targetPort: 8000
  recommendation:
    name: recommendation-service
    port: 8000       # Cambiar a 8000
    targetPort: 8000
  frontend:
    name: chef-frontend
    port: 80
    targetPort: 80   # El frontend sigue en el 80 (Nginx)