{{- range $key, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
spec:
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      containers:
      - name: {{ $service.name }}
        image: {{ $service.image }}
        ports:
        - containerPort: {{ $service.targetPort | default 8000 }} # Usa targetPort (8000 o 80)
        env:
        - name: PORT
          value: {{ $service.targetPort | quote }} # El contenedor escucha en el targetPort
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq-service:5672" # Usa el nombre del servicio interno
        # --- AÑADE ESTO AQUÍ ---
        - name: KEYCLOAK_URL
          value: "https://keycloak.ltu-m7011e-5.se"
        # -----------------------
{{- end }}