{{- range $key, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  namespace: todo-app
  labels:
    app: {{ $service.name }}
spec:
  replicas: {{ $service.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      containers:
      - name: {{ $service.name }}
        image: {{ $service.image }}
        ports:
        - containerPort: {{ $service.targetPort | default 8000 }}
        env:
        - name: PORT
          value: {{ $service.targetPort | default 8000 | quote }}
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq-service:5672"
        - name: KEYCLOAK_URL
          value: "https://keycloak.ltu-m7011e-5.se"
        - name: KEYCLOAK_REALM
          value: "ChefMatchRealm"
---
{{- end }}