{{- range $key, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
spec:
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      containers:
      - name: {{ $service.name }}
        image: {{ $service.image }}
        ports:
        - containerPort: {{ $service.port | default 80 }}
        env:
        - name: PORT
          value: {{ $service.port | quote }}
        # ESTA ES LA L√çNEA CLAVE PARA CONECTAR CON RABBITMQ (REQ15)
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq-service:5672"
{{- end }}