{{- range $key, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
spec:
  # ... selector y template ...
    spec:
      containers:
      - name: {{ $service.name }}
        image: {{ $service.image }}
        ports:
        - containerPort: {{ $service.targetPort | default 8000 }}
        env:
        - name: PORT
          value: {{ $service.targetPort | quote }}
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq-service:5672"
        # --- AÃ‘ADE ESTA VARIABLE OBLIGATORIA ---
        - name: KEYCLOAK_URL
          value: "https://keycloak.ltu-m7011e-5.se"
        # ---------------------------------------
{{- end }}