apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chef-match-ingress
  namespace: todo-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1  # VITAL para limpiar el /api/
spec:
  rules:
  - host: ltu-m7011e-5.se
    http:
      paths:
      - path: /api/recipes/(.*)   # Captura todo lo de recetas
        pathType: Prefix
        backend:
          service:
            name: recipe-service
            port:
              number: 80
      - path: /api/users/(.*)     # Captura todo lo de usuarios/preferencias
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80
      - path: /()(.*)             # Todo lo dem√°s al frontend
        pathType: Prefix
        backend:
          service:
            name: chef-frontend
            port:
              number: 80