spec:
  rules:
  - host: ltu-m7011e-5.se
    http:
      paths:
      - path: /recipes
        pathType: Prefix
        backend:
          service:
            name: recipe-service
            port:
              number: 80
      - path: /recommendations
        pathType: Prefix
        backend:
          service:
            name: recommendation-service
            port:
              number: 80
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chef-frontend
            port:
              number: 80