apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chef-match-ingress
  namespace: todo-app
  annotations:
    kubernetes.io/ingress.class: traefik
    # Esta anotación es clave para que /recipes llegue como / al backend si no has cambiado las rutas
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip 
spec:
  rules:
  - host: ltu-m7011e-5.se
    http:
      paths:
      - path: /recipes
        pathType: ImplementationSpecific
        backend:
          service:
            name: recipe-service
            port:
              number: 8000 # CAMBIADO de 80 a 8000
      - path: /users
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-service
            port:
              number: 8000 # CAMBIADO de 80 a 8000
              # ... debajo de /users añade esto:
      - path: /recommendations
        pathType: Prefix
        backend:
          service:
            name: recommendation-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chef-frontend
            port:
              number: 80