apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chef-api-ingress
  namespace: todo-app
  annotations:
    kubernetes.io/ingress.class: traefik
    # Prioridad máxima para las APIs
    traefik.ingress.kubernetes.io/router.priority: "1000"
spec:
  ingressClassName: traefik
  rules:
  - host: ltu-m7011e-5.se
    http:
      paths:
      - path: /recipes
        pathType: Exact
        backend:
          service:
            name: recipe-service
            port:
              number: 8000
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 8000
      - path: /recommendations
        pathType: Prefix
        backend:
          service:
            name: recommendation-service
            port:
              number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chef-frontend-ingress
  namespace: todo-app
  annotations:
    kubernetes.io/ingress.class: traefik
    # Prioridad mínima para el Frontend (catch-all)
    traefik.ingress.kubernetes.io/router.priority: "1"
spec:
  ingressClassName: traefik
  rules:
  - host: ltu-m7011e-5.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chef-frontend
            port:
              number: 80