apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: chefmatch
type: Opaque
stringData:
  rabbitmq-url: "amqp://guest:guest@rabbitmq-service:5672"
  mongo-uri: "mongodb://mongo-service.chefmatch.svc.cluster.local:27017/chefmatch"
  keycloak-url: "https://keycloak.ltu-m7011e-5.se"
  keycloak-realm: "ChefMatchRealm"
  keycloak-client-id: "account"