{{- range $key, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
spec:
  selector:
    app: {{ $service.name }}
  ports:
  - port: {{ $service.port }}
    targetPort: {{ $service.port }}
  type: ClusterIP
{{- end }}