apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.user_service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.user_service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.user_service.name }}
    spec:
      containers:
      - name: user-service
        image: {{ .Values.user_service.image }}
        ports:
        - containerPort: {{ .Values.user_service.port }}
        env:
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq-service:5672"