name: CI - Chef Match Microservices

on:
  push:
    branches: [ main ]

jobs:
  test-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, recipe-service, recommendation-service]
    steps:
      - name: ‚¨áÔ∏è Checkout code
        uses: actions/checkout@v4
      - name: üü¢ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: üß™ Run Tests
        run: |
          cd services/${{ matrix.service }}
          npm install
          npm test -- --coverage

  build-and-push:
    runs-on: ubuntu-latest
    needs: test-services
    strategy:
      matrix:
        # Aqu√≠ incluimos todos
        service: [user-service, recipe-service, recommendation-service, frontend]
    steps:
      - name: ‚¨áÔ∏è Checkout code
        uses: actions/checkout@v4

      - name: üîë Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: üî® Build and Push
        uses: docker/build-push-action@v5
        with:
          # Esta l√≠nea es la clave: 
          # Si el servicio es 'frontend', busca en la ra√≠z. Si no, busca en 'services/'
          context: ${{ matrix.service == 'frontend' && './frontend' || format('./services/{0}', matrix.service) }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/chef-${{ matrix.service }}:latest